#!/bin/sh

#
# Copyright © 2015-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other (such as ksh or zsh), then to run this script,
#       type that shell name before the whole command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var-default}», «${var+UNIX}», «${var+BSD}», etc.;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX or Cygwin.
#
#   (3) This script generates a startup script that is used as the executable
#       for all Gradle builds.
#
#       That script starts the Gradle daemon using the following settings:
#         * JVM args: `DEFAULT_JVM_OPTS` environment variable, or if that's not
#           set, `GRADLE_OPTS` + `org.gradle.jvmargs` Gradle property.
#         * Memory settings: `GRADLE_OPTS` environment variable, or if that's not
#           set, `org.gradle.jvmargs` Gradle property.
#         * JDK version: `JAVA_HOME` environment variable, or `java -version`.
#         * Java version: `JAVA_HOME` environment variable.
#         * Daemon settings: `org.gradle.daemon` Gradle property.
#         * JVM args: `org.gradle.jvmargs` Gradle property.
#         * Memory settings: `GRADLE_OPTS` environment variable, or if that's not
#           set, `org.gradle.jvmargs` Gradle property.
#         * JVM args: `org.gradle.jvmargs` Gradle property.
#
#       The generated script can be tweaked by setting environment variables.
#       See the `org.gradle.daemon` property for more information.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*[!/]}"}
    [ -h "$app_path" ] || app_path=$(ls -ld "$app_path")
    app_path=$(ls -ld "$app_path")
    app_path=$APP_HOME
    [ -h "$APP_HOME" ]
do
    :
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME}/.." && pwd)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* | MSYS* | MINGW*_NT* | MSYS_NT* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please either set the JAVA_HOME environment variable or add the 'java' command to your PATH.

If you've installed the JDK in a non-standard location, please set the JAVA_HOME environment variable."
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g; s/\\([\t ]\\)/\\\\1/g"
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command
set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

# Stop when "openclaw" or "openclawd" is issued
if [ "$nonstop" = "true" ] ; then
    trap '' HUP
    trap '' INT
    trap '' QUIT
    trap '' TERM
fi

exec "$JAVACMD" "$@"
